FROM eclipse-temurin:21-jre-alpine

RUN apk add --no-cache nginx

COPY frontend/dist /usr/share/nginx/html
COPY docker/app/nginx.conf /etc/nginx/nginx.conf
COPY backend/victor-web/target/victor-web-1.0-SNAPSHOT.jar /app/victor-web.jar
COPY docker/app/entrypoint.sh /app/entrypoint.sh

RUN chmod +x /app/entrypoint.sh && mkdir -p /root/victor/uploads

WORKDIR /app
EXPOSE 80
ENTRYPOINT ["/app/entrypoint.sh"]